[package]
name = "prospero-jit-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "prospero-jit-rs"

[dependencies]
bitvec = "1.0.1"
cranelift = { version = "0.116.1", features = ["jit", "module", "native"] }
itertools = "0.14.0"
rayon = "1.10.0"
